config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get :'signin', to: 'sessions#new'
  delete :'signout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  resources :articles do
    get :favourite, on: :member
    resources :comments
  end
  get 'auth/vkontakte/callback', to: 'omniauth#create'
  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :articles, only: [:index, :destroy]
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :favourite_posts
  has_and_belongs_to_many :categories
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  paginates_per 10
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminsController
  def index
    @articles = Article.all
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, only: [:index, :edit, :update]
  before_action :current_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @articles = params[:current] ? current_user.articles.includes(:categories).page(params[:page]) : Article.all.includes(:categories).page(params[:page])
  end

  def show
    @article.increment!(:page_views)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to @article
  end

  def favourite
    current_user.favourite_posts.manage(@article)
  end

  private

  def current_post
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :integer, :image, category_ids: [])
  end

  def require_user
    redirect_to root_path unless @article.user == current_user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def favourite_post(article)
    if current_user.favourite_posts.map(&:article).include?(article)
      'text-muted'
    else
      'text-success'
    end
  end
end

app/views/admin/articles/destroy.js.erb
$('#article_<%=@article.id %>').remove()

app/views/admin/articles/index.html.slim
- provide(:title, 'Articles list')
h1
  | List of articles
.row
  center
    = link_to 'New article', new_article_path, class:'btn btn-info'
.col-md-8.col-md-offset-2
  table.table
    thead
      tr
        th
          | Title
        th
          | Text
        th
          | Action
        th
          | Category
    - @articles.each do |article|
      |  <tr id = 
      = "article_#{article.id}"
      | > 
      td
        = article.title
      td
        = article.text
      td
        = link_to 'Delete', admin_article_path(article), class:'btn btn-info',
                            method: :delete,
                            remote: true,
                            data: { confirm: 'Are you sure?' }
        = link_to 'Show ', article_path(article)
      td
        - article.categories.each do |category|
          b
            = category.name
      