config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get :'signin', to: 'sessions#new'
  delete :'signout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  resources :articles do
    get :favourite, on: :member
    resources :comments
  end
  get 'auth/vkontakte/callback', to: 'omniauth#create'
  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :articles, only: [:index, :destroy]
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :favourite_posts
  has_and_belongs_to_many :categories
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  paginates_per 10
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminsController
  def index
    @articles = Article.all
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, only: [:index, :edit, :update]
  before_action :current_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @articles = params[:current] ? current_user.articles.includes(:categories).page(params[:page]) : Article.all.includes(:categories).page(params[:page])
  end

  def show
    @article.increment!(:page_views)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to @article
  end

  def favourite
    current_user.favourite_posts.manage(@article)
  end

  private

  def current_post
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :integer, :image, category_ids: [])
  end

  def require_user
    redirect_to root_path unless @article.user == current_user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def favourite_post(article)
    if current_user.favourite_posts.map(&:article).include?(article)
      'text-muted'
    else
      'text-success'
    end
  end
end

app/views/articles/_form.html.slim
.row
  .col-md-8.col-md-offset-2
    = form_for @article do |f|
      - if @article.errors.any?
        #error_explanation
          h2
            = pluralize(@article.errors.count, "error")
            |  prohibited this article from being saved: 
          ul
            - @article.errors.full_messages.each do |msg|
              li
                = msg
      = f.label :title
      = f.text_field :title
      = f.label :text
      = f.text_area :text
      = f.label :image
      = f.file_field :image
      =f.label :category_ids
      =f.collection_check_boxes :category_ids, Category.all, :id, :name
      br
      = f.submit "Create my article", class: "btn btn-primary"

app/views/articles/edit.html.slim
- provide(:title, 'Edit Article')
.row
  .col-md-4.col-md-offset-4
    h1
      | Editing article
    = form_for :article, url: article_path(@article), method: :patch do |f|
      - if @article.errors.any?
        #error_explanation
          h2
            = pluralize(@article.errors.count, "error")
            |  prohibited this article from being saved: 
          ul
            - @article.errors.full_messages.each do |msg|
              li
                = msg
      = f.label :title
      = f.text_field :title
      = f.label :text
      = f.text_area :text
      = f.label :image
      = f.file_field :image
      =f.label :category_ids
      =f.collection_check_boxes :category_ids, Category.all, :id, :name
      br
      = f.submit 'Edit Article', class:'btn btn-large btn-info'
    = link_to 'Back', articles_path

app/views/articles/favourite.js.erb
$('#article_<%= @article.id %>').toggleClass('text-success').toggleClass('text-muted');

app/views/articles/index.html.slim
- provide(:title, 'Articles list')
h1
  | Listing articles
.row
  center
    = link_to 'New article', new_article_path(current_user), class:'btn btn-lg btn-info'
    - @articles.each do |article|
      p
      h2
        | Title
      p
        = article.title
      p
      h2
        | Text
      p
        = article.text
      p
        = image_tag article.image.url(:medium)
      .categories
        h4
          | Category:
        - article.categories.each do |category|
          b
            = category.name
      br
      = link_to 'Show', article_path(article)
      - if article.user == current_user
        = link_to 'Edit', edit_article_path(article)
        = link_to 'Destroy', article_path(article),
                            method: :delete,
                            data: { confirm: 'Are you sure?' }
.row
  center
    = paginate @articles

app/views/articles/new.html.slim
- provide(:title, 'New Article')
h1
  | New Article
= render 'form'
.row
  .my-link.col-md-4.col-md-offset-4 
   br
    = link_to 'Back', user_path(current_user) , class:'btn btn-info'

app/views/articles/show.html.slim
- provide(:title, @article.title)
center
  .row
    .col-md-6.col-md-offset-3
      p
        b
          |  Количество просмотров 
          = @article.page_views
      h4
        | Title:
      p
        = @article.title
      h4
        | Text:
      p
        = @article.text
      .categories
        h4
          | Category:
        - @article.categories.each do |category|
          b
            =category.name
      p
        = image_tag @article.image.url(:medium)
      - if @article.user == current_user
        = link_to 'Edit', edit_article_path
        |  | 
        = link_to 'Back', root_path
      - else
        = link_to 'Back', root_path
      br
    .row
      .col-md-4.col-md-offset-4
        h3
          = @article.comments.count
          |  Comments
        = render @article.comments
        - if current_user
          h4
            | Add a comment:
          = render 'comments/form'