config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get :'signin', to: 'sessions#new'
  delete :'signout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  resources :articles do
    get :favourite, on: :member
    resources :comments
  end
  get 'auth/vkontakte/callback', to: 'omniauth#create'
  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :articles, only: [:index, :destroy]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :favourite_posts
  has_and_belongs_to_many :categories
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  paginates_per 10
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
  has_many :catetegories_articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/favourite_post.rb
class FavouritePost < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  def self.manage(article)
    object = find_by(article: article)
    object ? object.destroy : create(article: article)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :articles, dependent: :destroy
  has_many :favourite_posts, dependent: :destroy
  has_many :accounts, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  paginates_per 10
end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin
    @current_user.try(:admin)
  end

  def authorize
    redirect_to signin_path, alert: 'Not authorize' if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, only: [:index, :edit, :update]
  before_action :current_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @articles = params[:current] ? current_user.articles.includes(:categories).page(params[:page]) : Article.all.includes(:categories).page(params[:page])
  end

  def show
    @article.increment!(:page_views)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to @article
  end

  def favourite
    current_user.favourite_posts.manage(@article)
  end

  private

  def current_post
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :integer, :image, category_ids: [])
  end

  def require_user
    redirect_to root_path unless @article.user == current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  def create
    @account = Account.find_by(email: auth_hash[:info][:email])
    if @account
    else
      @user = User.find_by(email: auth_hash[:info][:email])
      if @user
        account_create
      else
        @user = User.new(vk_params)
        account_create
        @account.save
        UserMailer.inviters_mailer(@user).deliver_now
        flash[:success] = 'Мы отправили письмо с Вашим паролем на Вашу почту. Спасибо за регистрацию!!!'
      end
    end
    session[:user_id] = @account.user_id
    redirect_to current_user
  end

  def account_create
    @account = Account.create(uid: auth_hash[:uid],
                              provider: auth_hash[:provider],
                              email: auth_hash[:info][:email],
                              user: @user)
  end

  private

  def vk_params
    password = "#{rand(100)}_sample_password_#{rand(100)}"
    { name: auth_hash[:info][:name],
      email: auth_hash[:info][:email],
      remote_avatar_url: auth_hash[:extra][:raw_info][:photo_200],
      password: password,
      password_confirmation: password
    }
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user, notice: 'Logged in'
    else
      flash.now.alert = 'invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @articles = Article.all.includes(:categories).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signin_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.all.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    if current_admin
      @user.update_attributes(user_params, admin: true)
    end
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:user_id] = @user.id
      redirect_to @user.email, notice: 'Thank you for signed up!!!'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_admin
      @user.update_attributes(user_params)
    end
    if current_user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to current_user
    else
      render'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :admin)
  end

  def signin_user
    @user = User.find(params[:id])
    redirect_to signin_path unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'This is my blog'
    if page_title.empty?
      base_title
    else
      "#{page_title}"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def favourite_post(article)
    if current_user.favourite_posts.map(&:article).include?(article)
      'text-muted'
    else
      'text-success'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/admin/application.html.slim
doctype html
html
  head
    title
      =full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'shared/admin/header'
    .my-container.container
      = yield
    = render 'shared/admin/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      =full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'shared/shim'
  body
    = render 'shared/header'
    .my-container.container
      = yield
      .my-flash.row
        .col-md-4.col-md-offset-4
          - flash.each do |name, msg|
            = content_tag :div, msg, id: 'flash_#{name}'
    = render 'shared/footer'

app/views/shared/_error_message.html.slim
- if current_user.errors.any?
  #error_explanation
    .alert.alert-error
      |  The form contains 
      = pluralize(current_user.errors.count, "error")
      | . 
    ul
      - current_user.errors.full_messages.each do |msg|
        li
          | * 
          = msg

app/views/shared/_footer.html.slim
footer.my-footer.navbar.navbar-fixed-bottom.navbar-inverse
  .navbar-inner
    .text-center
      nav
        ul.my-footnav.nav.navbar-nav
          li
            = link_to "О сервисе",   '#'
          li
            = link_to "Наши контакты", '#'
        ul.my-footnav.nav.navbar-nav.pull-right
          li
            = link_to 'auth/vkontakte' do
              | Регистрация через 
              i.fa.fa-vk.fa-2x

app/views/shared/_header.html.slim
header.my-header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to root_path, id: "logo" do
        = image_tag "Logo2.png", alt: 'Ruby blogger'
      end
      nav
        ul.my-nav.nav.navbar-nav.pull-right
          li
            = link_to "Список пользователей", users_path
          - if current_admin
            li
              = link_to "Admin", admin_root_path
          li
          - if current_user
            li
              a.dropdown-toggle[href="#" data-toggle="dropdown"]
                |  Account 
                b.caret
              ul.header_menu.dropdown-menu
                li
                  = link_to "Profile", current_user
                li
                  = link_to "Update_profile", edit_user_path(current_user)
                li
                  = link_to "My_Article", articles_path(current: true)
                li.divider
                li
                  = link_to "Sign Out", signout_path, method: "delete", class: "btn btn-large btn-primary"
          - else
            li
              = link_to "Войти", signin_path
            li
              = link_to "Регистрация", new_user_path, class: "btn btn-large btn-primary"

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/shared/admin/_footer.html.slim
footer.my-footer.navbar.navbar-fixed-bottom.navbar-inverse

app/views/shared/admin/_header.html.slim
header.my-header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to root_path, id: "logo" do
        = image_tag 'Logo2.png', alt: 'Ruby blogger'
      end
      nav
        ul.my-nav.nav.navbar-nav.pull-right
          li
            = link_to "List of Users", admin_users_path
          li
            = link_to "Back to site", root_url
          li
            = link_to 'All articles', admin_articles_path